# Generated by Django 5.2.3 on 2025-10-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_person_how_did_you_learn_about_iasd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LanguagesProficiencyLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_contact_email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='person',
            name='native_language',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='preferred_languages',
        ),
        migrations.AddField(
            model_name='country',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries_as_native_language', to='people.language'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_studing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_with_nationality', to='people.nationality'),
        ),
        migrations.CreateModel(
            name='PersonLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_preferred_languages', to='people.language')),
                ('language_proficiency_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_proficiency_level', to='people.languagesproficiencylevels')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_languages', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='people.person')),
            ],
            options={
                'ordering': ('-is_primary', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='unique_primary_emergency_contact_per_person')],
            },
        ),
        migrations.CreateModel(
            name='PersonHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('diagnosed_on', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people_with_condition', to='people.healthcondition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_statuses', to='people.person')),
            ],
            options={
                'ordering': ('-is_current', '-diagnosed_on', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('person',), name='unique_current_health_status_per_person')],
            },
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=400)),
                ('image_name', models.CharField(max_length=400)),
                ('captured_on', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='people.person')),
            ],
            options={
                'ordering': ('-is_primary', '-captured_on', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='unique_primary_photo_per_person')],
            },
        ),
    ]
