# Generated by Django 5.2.3 on 2025-10-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_degree_personattributetype_relationshiptype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marriage',
            table=None,
        ),
    ]
