# Generated by Django 5.2.3 on 2025-11-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_marriage_table'),
    ]

    operations = []
