# Generated by Django 5.2.3 on 2025-11-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_rename_name_family_first_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='second_last_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_with_second_last_name', to='people.lastname'),
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_with_second_name', to='people.personname'),
        ),
    ]
