# Generated by Django 5.2.3 on 2025-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_nickname_person_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
