# Generated by Django 5.2.3 on 2025-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_country_code_alter_language_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='code',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='label',
            field=models.CharField(max_length=150),
        ),
    ]
