# Generated by Django 5.2.3 on 2025-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_occupation_code_alter_occupation_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
