# Generated by Django 5.2.3 on 2025-11-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_city_name_alter_state_code_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
